language: go

go:
    - "1.8.2"

sudo: false

# env:
#     global:
#         - SSH_KEY="id_rsa"
#         - GIT_NAME="Roman Coedo"
#         - GIT_EMAIL="romancoedo@gmail.com"
#         - SOURCE_DIR="public"
#         - DEPLOY_BRANCH="source"

# before_install:
#     - openssl aes-256-cbc -K $encrypted_5badef0aa7c9_key -iv $encrypted_5badef0aa7c9_iv -in id_rsa.enc -out id_rsa -d

branches:
    only:
        - master

before_script:
    # - git clone --branch v2 https://github.com/go-yaml/yaml $GOPATH/src/gopkg.in/yaml.v2
    - git clone -b 'v0.21' --single-branch --depth 1 https://github.com/spf13/hugo.git $GOPATH/src/github.com/spf13/hugo
    - ls -la $GOPATH/src
    - go get -u -v github.com/spf13/hugo
    - ls -la $GOPATH/src

script:
    # - git clone https://github.com/rcoedo/hugo-steam-theme ./themes/hugo-steam-theme
    - hugo version
    - hugo

# after_success:
#     - echo "rcoedo.com" > ./public/CNAME
    # - ./scripts/deploy.sh

deploy:
    provider: pages
    local_dir: public
    skip_cleanup: true
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    on:
        branch: master
