language: go

go:
    - "1.8.2"

sudo: false
dist: xenial

# env:
#     global:
#         - SSH_KEY="id_rsa"
#         - GIT_NAME="Roman Coedo"
#         - GIT_EMAIL="romancoedo@gmail.com"
#         - SOURCE_DIR="public"
#         - DEPLOY_BRANCH="source"

# before_install:
#     - openssl aes-256-cbc -K $encrypted_5badef0aa7c9_key -iv $encrypted_5badef0aa7c9_iv -in id_rsa.enc -out id_rsa -d

before_script:
    # - git clone --branch v2 https://github.com/go-yaml/yaml $GOPATH/src/gopkg.in/yaml.v2
    - go get -u -v github.com/spf13/hugo

script:
    # - git clone https://github.com/rcoedo/hugo-steam-theme ./themes/hugo-steam-theme
    - hugo version

# after_success:
#     - echo "rcoedo.com" > ./public/CNAME
    # - ./scripts/deploy.sh
