language: go

go:
    - "1.8.2"

sudo: false

branches:
    only:
        - master

before_script:
    - git clone -b 'v0.21' --single-branch --depth 1 https://github.com/spf13/hugo.git $GOPATH/src/github.com/spf13/hugo
    - ls -la $GOPATH/src
    - go get -u -v github.com/spf13/hugo
    - ls -la $GOPATH/src

script:
    - hugo version
    - hugo

deploy:
    provider: pages
    local_dir: public
    skip_cleanup: true
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    fqdn: indragunawan.github.io
    on:
        branch: master
